# Generated by Django 3.1.1 on 2020-10-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_type', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=25)),
                ('dor', models.DateTimeField()),
                ('address', models.CharField(max_length=25)),
                ('cartype', models.CharField(max_length=25)),
                ('regno', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
