# Generated by Django 3.1.1 on 2020-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('cartype', models.CharField(max_length=25)),
                ('regno', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
