# Generated by Django 3.1.1 on 2020-10-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_auto_20201026_2314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='cusers',
        ),
    ]
