# Generated by Django 3.1.1 on 2020-10-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_auto_20201026_2320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
