# Generated by Django 3.1.1 on 2020-10-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_auto_20201026_2321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
