# Generated by Django 3.1.1 on 2020-10-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_auto_20201026_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
