# Generated by Django 3.1.1 on 2020-12-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0009_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.EmailField(max_length=100)),
                ('name', models.EmailField(max_length=125)),
                ('regno', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
                ('msg', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
