# Generated by Django 3.1.1 on 2020-12-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0011_auto_20201205_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=225),
        ),
    ]
