# Generated by Django 3.1.1 on 2020-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0012_auto_20201205_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compactsuv',
            fields=[
                ('car_type', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('intextwash', models.CharField(max_length=20)),
                ('compwash', models.CharField(max_length=20)),
                ('intdet', models.CharField(max_length=20)),
                ('extdet', models.CharField(max_length=20)),
                ('silver', models.CharField(max_length=20)),
                ('gold', models.CharField(max_length=20)),
                ('washtime', models.TimeField()),
                ('dettime', models.TimeField()),
            ],
            options={
                'db_table': 'Compactsuv',
            },
        ),
        migrations.CreateModel(
            name='Hatchback',
            fields=[
                ('car_type', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('intextwash', models.CharField(max_length=20)),
                ('compwash', models.CharField(max_length=20)),
                ('intdet', models.CharField(max_length=20)),
                ('extdet', models.CharField(max_length=20)),
                ('silver', models.CharField(max_length=20)),
                ('gold', models.CharField(max_length=20)),
                ('washtime', models.TimeField()),
                ('dettime', models.TimeField()),
            ],
            options={
                'db_table': 'Hatchback',
            },
        ),
        migrations.CreateModel(
            name='Sedan',
            fields=[
                ('car_type', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('intextwash', models.CharField(max_length=20)),
                ('compwash', models.CharField(max_length=20)),
                ('intdet', models.CharField(max_length=20)),
                ('extdet', models.CharField(max_length=20)),
                ('silver', models.CharField(max_length=20)),
                ('gold', models.CharField(max_length=20)),
                ('washtime', models.TimeField()),
                ('dettime', models.TimeField()),
            ],
            options={
                'db_table': 'Sedan',
            },
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('car_type', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('intextwash', models.CharField(max_length=20)),
                ('compwash', models.CharField(max_length=20)),
                ('intdet', models.CharField(max_length=20)),
                ('extdet', models.CharField(max_length=20)),
                ('silver', models.CharField(max_length=20)),
                ('gold', models.CharField(max_length=20)),
                ('washtime', models.TimeField()),
                ('dettime', models.TimeField()),
            ],
            options={
                'db_table': 'Suv',
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
