# Generated by Django 3.1.1 on 2020-12-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0016_appointment_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Washtime',
            field=models.TimeField(default="66"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='dettime',
            field=models.TimeField(default="66"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='Washtime',
            field=models.TimeField(default="66"),
            preserve_default=False,
        ),
    ]
