# Generated by Django 3.1.1 on 2020-12-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0021_auto_20201213_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package',
        ),
    ]
