# Generated by Django 3.1.1 on 2020-12-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0022_remove_package_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100)),
                ('name', models.EmailField(max_length=125)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
    ]
