# Generated by Django 3.1.4 on 2021-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0023_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
