# Generated by Django 3.1.4 on 2021-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0024_auto_20210103_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dettime',
            field=models.CharField(default=0.0004950495049504951, max_length=25),
            preserve_default=False,
        ),
    ]
